server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/escape_room_db
    username: escape_room_user
    password: escape_room_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect